/**
 * Backups Documentation - Constants
 */

import { DatabaseBackup, HardDrive, FileText, Shield } from 'lucide-react'
import type { BackupType, RetentionInfo, SecurityFeature, BestPractice } from './types'

export const BACKUP_TYPES: BackupType[] = [
  {
    name: 'Database Backups',
    icon: DatabaseBackup,
    color: 'blue',
    description: 'Complete PostgreSQL database dump for your project\'s tenant schema',
    features: [
      'Manual export via API',
      'SQL dump generated by pg_dump',
      'Gzip compression enabled',
      'Sent to Telegram for storage',
      'Tracked in backup history',
    ],
    useCases: [
      'Before major schema changes',
      'Before data migrations',
      'For disaster recovery',
      'For creating development environments',
    ],
  },
  {
    name: 'Storage Backups',
    icon: HardDrive,
    color: 'orange',
    description: 'Large files stored in Telegram with automatic handling',
    features: [
      'Automatic for files >2GB',
      'Telegram built-in backup mechanism',
      'No manual intervention required',
      'Redundant cloud storage',
    ],
    useCases: [
      'Long-term file archival',
      'Large asset preservation',
      'Redundant storage for critical files',
    ],
  },
  {
    name: 'Logs Backups',
    icon: FileText,
    color: 'purple',
    description: 'Application and audit logs archived via Telegram',
    features: [
      'Export via API endpoint',
      'JSON or text format',
      'Date range filtering',
      'Sent to Telegram storage',
      'Compliance and security auditing',
    ],
    useCases: [
      'Compliance requirements',
      'Security investigations',
      'Performance analysis',
      'Historical troubleshooting',
    ],
  },
]

export const RETENTION_INFO: RetentionInfo = {
  policy: '30 days',
  warning: '7 days before expiration',
  cleanup: 'Automatic background job',
  notification: 'Sent before deletion',
}

export const SECURITY_FEATURES: SecurityFeature[] = [
  {
    icon: Shield,
    title: 'Authentication Required',
    description: 'All backup endpoints require valid JWT token with proper scopes',
  },
  {
    icon: Shield,
    title: 'Project-Level Permissions',
    description: 'Users can only backup their own projects',
  },
  {
    icon: Shield,
    title: 'Encrypted Transmission',
    description: 'Backups transmitted via HTTPS/TLS 1.3',
  },
  {
    icon: Shield,
    title: 'Audit Trail',
    description: 'All backup operations logged to project_logs',
  },
]

export const BEST_PRACTICES: BestPractice[] = [
  {
    category: 'Before Creating Backups',
    items: [
      'Verify sufficient storage space',
      'Check for ongoing migrations or deployments',
      'Notify team members of planned backup',
      'Document backup purpose and retention need',
    ],
  },
  {
    category: 'After Creating Backups',
    items: [
      'Verify backup completed successfully',
      'Check backup size is reasonable',
      'Confirm backup appears in history',
      'Test restore on non-production environment',
    ],
  },
  {
    category: 'Backup Security',
    items: [
      'Never share backup files via unencrypted channels',
      'Delete local copies after upload to Telegram',
      'Rotate JWT tokens regularly',
      'Monitor backup access logs',
    ],
  },
]

export const BACKUP_COLOR_CLASSES: Record<string, string> = {
  blue: 'bg-blue-100 text-blue-700 border-blue-200',
  orange: 'bg-orange-100 text-orange-700 border-orange-200',
  purple: 'bg-purple-100 text-purple-700 border-purple-200',
}
