/**
 * Errors Documentation - Constants
 */

import { Ban, FileQuestion, XCircle, RefreshCw, AlertCircle, Lock, Shield } from 'lucide-react'
import type { ErrorDoc } from './types'

export const ERROR_DOCS: ErrorDoc[] = [
  {
    code: 'PROJECT_SUSPENDED',
    title: 'Project Suspended',
    httpStatus: 403,
    retryable: false,
    description: 'The project has been suspended due to abuse detection, hard cap violations, or administrative action.',
    commonCauses: [
      'Exceeded daily hard caps (DB queries, storage uploads, function invocations)',
      'Abuse patterns detected (SQL injection attempts, auth brute force)',
      'Administrative suspension',
    ],
    solutions: [
      'Review the suspension notification email for details',
      'Contact support to resolve the issue',
      'Reduce usage to stay within quotas after reinstatement',
    ],
    icon: Ban,
    color: 'red',
  },
  {
    code: 'PROJECT_ARCHIVED',
    title: 'Project Archived',
    httpStatus: 403,
    retryable: false,
    description: 'The project has been archived and is no longer accessible.',
    commonCauses: ['Project was manually archived', 'Account was closed'],
    solutions: [
      'Restore the project from the dashboard if within retention period',
      'Contact support for assistance',
    ],
    icon: FileQuestion,
    color: 'gray',
  },
  {
    code: 'PROJECT_DELETED',
    title: 'Project Deleted',
    httpStatus: 404,
    retryable: false,
    description: 'The project has been permanently deleted.',
    commonCauses: ['Project was manually deleted', 'Account was terminated'],
    solutions: ['Create a new project', 'Contact support if deletion was accidental'],
    icon: XCircle,
    color: 'gray',
  },
  {
    code: 'RATE_LIMITED',
    title: 'Rate Limited',
    httpStatus: 429,
    retryable: true,
    description: 'Too many requests were made within a short time period.',
    commonCauses: [
      'Exceeded rate limit per minute/hour/day',
      'Burst traffic patterns',
      'Improper error handling causing retry loops',
    ],
    solutions: [
      'Implement exponential backoff for retries',
      'Check the Retry-After header in the response',
      'Reduce request frequency',
      'Use batching for bulk operations',
    ],
    icon: RefreshCw,
    color: 'orange',
  },
  {
    code: 'QUOTA_EXCEEDED',
    title: 'Quota Exceeded',
    httpStatus: 429,
    retryable: false,
    description: 'Monthly quota limits have been reached.',
    commonCauses: [
      'Exceeded monthly DB query quota',
      'Exceeded monthly storage quota',
      'Exceeded monthly function invocation quota',
    ],
    solutions: [
      'Wait for quota reset at the beginning of next month',
      'Upgrade to a higher tier plan',
      'Optimize queries to reduce usage',
    ],
    icon: AlertCircle,
    color: 'orange',
  },
  {
    code: 'KEY_INVALID',
    title: 'Invalid API Key',
    httpStatus: 401,
    retryable: false,
    description: 'The API key provided is invalid, expired, or revoked.',
    commonCauses: [
      'API key was revoked or rotated',
      'API key expired',
      'Incorrect API key in request headers',
    ],
    solutions: [
      'Verify the API key in your dashboard',
      'Generate a new API key if needed',
      'Check that the key is correctly set in Authorization header',
    ],
    icon: Lock,
    color: 'red',
  },
  {
    code: 'SERVICE_DISABLED',
    title: 'Service Disabled',
    httpStatus: 403,
    retryable: false,
    description: 'A specific service (Database, Storage, Realtime, etc.) is not enabled for this project.',
    commonCauses: ['Service not enabled in project settings', 'Service was disabled after trial period'],
    solutions: [
      'Enable the service from the project dashboard',
      'Check service availability for your plan',
    ],
    icon: Ban,
    color: 'purple',
  },
  {
    code: 'PERMISSION_DENIED',
    title: 'Permission Denied',
    httpStatus: 403,
    retryable: false,
    description: 'Insufficient permissions to perform the requested action.',
    commonCauses: [
      'Attempting to access another project\'s resources',
      'User role does not have required permissions',
      'Attempting to access admin-only endpoints',
    ],
    solutions: [
      'Verify you have the correct project selected',
      'Check your user role and permissions',
      'Contact project owner for access',
    ],
    icon: Shield,
    color: 'red',
  },
  {
    code: 'AUTHENTICATION_ERROR',
    title: 'Authentication Error',
    httpStatus: 401,
    retryable: false,
    description: 'Authentication is required or the provided credentials are invalid.',
    commonCauses: ['Missing or invalid JWT token', 'Token expired', 'Invalid email/password combination'],
    solutions: [
      'Sign in again to get a fresh token',
      'Verify your credentials',
      'Check that Authorization header is set correctly',
    ],
    icon: Lock,
    color: 'red',
  },
  {
    code: 'VALIDATION_ERROR',
    title: 'Validation Error',
    httpStatus: 400,
    retryable: false,
    description: 'The request contains invalid data or parameters.',
    commonCauses: [
      'Invalid query parameters',
      'Missing required fields',
      'Invalid data format',
      'Schema validation failed',
    ],
    solutions: [
      'Check the error details for specific validation issues',
      'Review API documentation for correct request format',
      'Ensure all required fields are included',
    ],
    icon: AlertCircle,
    color: 'yellow',
  },
  {
    code: 'NOT_FOUND',
    title: 'Not Found',
    httpStatus: 404,
    retryable: false,
    description: 'The requested resource does not exist.',
    commonCauses: ['Resource was deleted', 'Incorrect resource ID', 'Invalid endpoint path'],
    solutions: [
      'Verify the resource ID is correct',
      'Check that the resource still exists',
      'Review the API documentation for correct endpoints',
    ],
    icon: FileQuestion,
    color: 'gray',
  },
  {
    code: 'CONFLICT',
    title: 'Conflict',
    httpStatus: 409,
    retryable: false,
    description: 'The request conflicts with existing data or state.',
    commonCauses: [
      'Resource already exists',
      'Duplicate unique field value',
      'Concurrent modification conflict',
    ],
    solutions: [
      'Check if resource already exists before creating',
      'Use unique identifiers for resources',
      'Implement optimistic locking for concurrent updates',
    ],
    icon: AlertCircle,
    color: 'yellow',
  },
  {
    code: 'INTERNAL_ERROR',
    title: 'Internal Server Error',
    httpStatus: 500,
    retryable: true,
    description: 'An unexpected error occurred on the server.',
    commonCauses: [
      'Temporary server issue',
      'Database connection problem',
      'Service temporarily unavailable',
    ],
    solutions: [
      'Retry the request with exponential backoff',
      'Check status page for service availability',
      'Contact support if issue persists',
    ],
    icon: AlertCircle,
    color: 'red',
  },
]

export const ERROR_COLOR_CLASSES = {
  red: 'bg-red-100 text-red-700 border-red-200',
  orange: 'bg-orange-100 text-orange-700 border-orange-200',
  yellow: 'bg-yellow-100 text-yellow-700 border-yellow-200',
  gray: 'bg-gray-100 text-gray-700 border-gray-200',
  purple: 'bg-purple-100 text-purple-700 border-purple-200',
} as const
