'use client'

import Link from 'next/link'
import { DatabaseBackup, ArrowLeft, Shield, Clock, HardDrive, FileText, CheckCircle2, AlertTriangle } from 'lucide-react'
import { motion } from 'framer-motion'

const backupTypes = [
  {
    name: 'Database Backups',
    icon: DatabaseBackup,
    color: 'blue',
    description: 'Complete PostgreSQL database dump for your project\'s tenant schema',
    features: [
      'Manual export via API',
      'SQL dump generated by pg_dump',
      'Gzip compression enabled',
      'Sent to Telegram for storage',
      'Tracked in backup history',
    ],
    useCases: [
      'Before major schema changes',
      'Before data migrations',
      'For disaster recovery',
      'For creating development environments',
    ],
  },
  {
    name: 'Storage Backups',
    icon: HardDrive,
    color: 'orange',
    description: 'Large files stored in Telegram with automatic handling',
    features: [
      'Automatic for files >2GB',
      'Telegram built-in backup mechanism',
      'No manual intervention required',
      'Redundant cloud storage',
    ],
    useCases: [
      'Long-term file archival',
      'Large asset preservation',
      'Redundant storage for critical files',
    ],
  },
  {
    name: 'Logs Backups',
    icon: FileText,
    color: 'purple',
    description: 'Application and audit logs archived via Telegram',
    features: [
      'Export via API endpoint',
      'JSON or text format',
      'Date range filtering',
      'Sent to Telegram storage',
      'Compliance and security auditing',
    ],
    useCases: [
      'Compliance requirements',
      'Security investigations',
      'Performance analysis',
      'Historical troubleshooting',
    ],
  },
]

const retentionInfo = {
  policy: '30 days',
  warning: '7 days before expiration',
  cleanup: 'Automatic background job',
  notification: 'Sent before deletion',
}

const securityFeatures = [
  {
    icon: Shield,
    title: 'Authentication Required',
    description: 'All backup endpoints require valid JWT token with proper scopes',
  },
  {
    icon: Shield,
    title: 'Project-Level Permissions',
    description: 'Users can only backup their own projects',
  },
  {
    icon: Shield,
    title: 'Encrypted Transmission',
    description: 'Backups transmitted via HTTPS/TLS 1.3',
  },
  {
    icon: Shield,
    title: 'Audit Trail',
    description: 'All backup operations logged to project_logs',
  },
]

const bestPractices = [
  {
    category: 'Before Creating Backups',
    items: [
      'Verify sufficient storage space',
      'Check for ongoing migrations or deployments',
      'Notify team members of planned backup',
      'Document backup purpose and retention need',
    ],
  },
  {
    category: 'After Creating Backups',
    items: [
      'Verify backup completed successfully',
      'Check backup size is reasonable',
      'Confirm backup appears in history',
      'Test restore on non-production environment',
    ],
  },
  {
    category: 'Backup Security',
    items: [
      'Never share backup files via unencrypted channels',
      'Delete local copies after upload to Telegram',
      'Rotate JWT tokens regularly',
      'Monitor backup access logs',
    ],
  },
]

export default function BackupsDocsPage() {
  return (
    <div className="min-h-screen bg-[#F3F5F7]">
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700&display=swap');
        :root { --font-sans: 'Plus Jakarta Sans', ui-sans-serif, system-ui, sans-serif; }
        .font-jakarta { font-family: var(--font-sans); }
      `}</style>

      <nav className="bg-white border-b border-slate-200">
        <div className="mx-auto max-w-[1180px] px-4 py-4 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-3">
            <div className="grid h-9 w-9 place-items-center rounded-lg bg-emerald-700 text-white shadow">
              <svg width="20" height="20" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M4 12c5 0 4-8 10-8 0 3 6 3 6 8s-6 5-6 8c-6 0-5-8-10-8Z" fill="currentColor" />
              </svg>
            </div>
            <span className="font-jakarta text-xl font-semibold tracking-tight text-slate-900">nextmavens</span>
          </Link>

          <div className="flex items-center gap-6">
            <Link href="/" className="text-sm text-slate-600 hover:text-slate-900">Home</Link>
            <Link href="/docs" className="text-sm text-slate-900 font-medium">Docs</Link>
            <Link href="/mcp" className="text-sm text-slate-600 hover:text-slate-900">MCP</Link>
            <Link href="/login" className="text-sm text-slate-600 hover:text-slate-900">Login</Link>
          </div>
        </div>
      </nav>

      <main className="mx-auto max-w-[1180px] px-4 py-12">
        <Link href="/docs" className="inline-flex items-center gap-2 text-slate-600 hover:text-slate-900 mb-8">
          <ArrowLeft className="w-4 h-4" />
          Back to Docs
        </Link>

        <div className="max-w-4xl">
          <div className="flex items-center gap-3 mb-6">
            <div className="p-3 bg-blue-100 rounded-xl">
              <DatabaseBackup className="w-6 h-6 text-blue-700" />
            </div>
            <h1 className="text-4xl font-semibold text-slate-900">Backup Strategy</h1>
          </div>
          <p className="text-xl text-slate-600 mb-12">
            Comprehensive backup solution for database, storage, and logs with Telegram integration
            for secure, long-term archival and easy restore capabilities.
          </p>

          {/* Backup Types */}
          <section className="mb-16">
            <h2 className="text-2xl font-semibold text-slate-900 mb-6">Backup Types</h2>
            <div className="space-y-6">
              {backupTypes.map((type) => {
                const Icon = type.icon
                const colorClasses = {
                  blue: 'bg-blue-100 text-blue-700 border-blue-200',
                  orange: 'bg-orange-100 text-orange-700 border-orange-200',
                  purple: 'bg-purple-100 text-purple-700 border-purple-200',
                }[type.color]

                return (
                  <motion.div
                    key={type.name}
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    className="bg-white rounded-xl p-6 border border-slate-200"
                  >
                    <div className="flex items-start gap-4 mb-4">
                      <div className={`p-3 rounded-lg ${colorClasses}`}>
                        <Icon className="w-6 h-6" />
                      </div>
                      <div className="flex-1">
                        <h3 className="text-xl font-semibold text-slate-900 mb-2">{type.name}</h3>
                        <p className="text-slate-600">{type.description}</p>
                      </div>
                    </div>

                    <div className="grid md:grid-cols-2 gap-6">
                      <div>
                        <h4 className="text-sm font-semibold text-slate-900 mb-2">Features</h4>
                        <ul className="space-y-1">
                          {type.features.map((feature) => (
                            <li key={feature} className="flex items-start gap-2 text-sm text-slate-600">
                              <CheckCircle2 className="w-4 h-4 text-emerald-600 flex-shrink-0 mt-0.5" />
                              {feature}
                            </li>
                          ))}
                        </ul>
                      </div>

                      <div>
                        <h4 className="text-sm font-semibold text-slate-900 mb-2">Use Cases</h4>
                        <ul className="space-y-1">
                          {type.useCases.map((useCase) => (
                            <li key={useCase} className="flex items-start gap-2 text-sm text-slate-600">
                              <ArrowLeft className="w-4 h-4 text-slate-400 flex-shrink-0 mt-0.5 rotate-180" />
                              {useCase}
                            </li>
                          ))}
                        </ul>
                      </div>
                    </div>
                  </motion.div>
                )
              })}
            </div>
          </section>

          {/* Retention Policy */}
          <section className="mb-16">
            <h2 className="text-2xl font-semibold text-slate-900 mb-6">Retention Policy</h2>
            <div className="bg-white rounded-xl p-6 border border-slate-200">
              <div className="flex items-start gap-4 mb-6">
                <div className="p-3 bg-amber-100 rounded-lg">
                  <Clock className="w-6 h-6 text-amber-700" />
                </div>
                <div>
                  <h3 className="text-lg font-semibold text-slate-900 mb-2">30-Day Default Retention</h3>
                  <p className="text-slate-600">
                    All backups are retained for 30 days by default. Automatic cleanup runs daily
                    to delete expired backups from both database records and Telegram storage.
                  </p>
                </div>
              </div>

              <div className="grid md:grid-cols-2 gap-4">
                <div className="bg-slate-50 rounded-lg p-4">
                  <div className="flex items-center gap-2 mb-2">
                    <AlertTriangle className="w-4 h-4 text-amber-600" />
                    <span className="text-sm font-semibold text-slate-900">Expiration Warning</span>
                  </div>
                  <p className="text-sm text-slate-600">
                    Notifications sent {retentionInfo.warning} before backup expiration
                  </p>
                </div>

                <div className="bg-slate-50 rounded-lg p-4">
                  <div className="flex items-center gap-2 mb-2">
                    <CheckCircle2 className="w-4 h-4 text-emerald-600" />
                    <span className="text-sm font-semibold text-slate-900">Automatic Cleanup</span>
                  </div>
                  <p className="text-sm text-slate-600">
                    Background job deletes expired backups daily
                  </p>
                </div>
              </div>
            </div>
          </section>

          {/* Security Features */}
          <section className="mb-16">
            <h2 className="text-2xl font-semibold text-slate-900 mb-6">Security Features</h2>
            <div className="bg-white rounded-xl p-6 border border-slate-200">
              <div className="grid md:grid-cols-2 gap-6">
                {securityFeatures.map((feature, index) => {
                  const Icon = feature.icon
                  return (
                    <div key={index} className="flex items-start gap-3">
                      <div className="p-2 bg-emerald-100 rounded-lg flex-shrink-0">
                        <Icon className="w-5 h-5 text-emerald-700" />
                      </div>
                      <div>
                        <h4 className="text-sm font-semibold text-slate-900 mb-1">{feature.title}</h4>
                        <p className="text-sm text-slate-600">{feature.description}</p>
                      </div>
                    </div>
                  )
                })}
              </div>
            </div>
          </section>

          {/* Best Practices */}
          <section className="mb-16">
            <h2 className="text-2xl font-semibold text-slate-900 mb-6">Best Practices</h2>
            <div className="space-y-4">
              {bestPractices.map((practice) => (
                <div key={practice.category} className="bg-white rounded-xl p-6 border border-slate-200">
                  <h3 className="text-lg font-semibold text-slate-900 mb-4">{practice.category}</h3>
                  <ul className="space-y-2">
                    {practice.items.map((item) => (
                      <li key={item} className="flex items-start gap-2 text-sm text-slate-600">
                        <CheckCircle2 className="w-4 h-4 text-emerald-600 flex-shrink-0 mt-0.5" />
                        {item}
                      </li>
                    ))}
                  </ul>
                </div>
              ))}
            </div>
          </section>

          {/* API Access */}
          <section className="mb-16">
            <h2 className="text-2xl font-semibold text-slate-900 mb-6">API Access</h2>
            <div className="bg-white rounded-xl p-6 border border-slate-200">
              <p className="text-slate-600 mb-4">
                Access backup functionality through your project dashboard or directly via API endpoints.
              </p>
              <div className="flex gap-4">
                <Link
                  href="/dashboard/backups"
                  className="inline-flex items-center gap-2 px-4 py-2 bg-emerald-700 text-white rounded-lg hover:bg-emerald-800 transition"
                >
                  <DatabaseBackup className="w-4 h-4" />
                  Go to Backup Dashboard
                </Link>
                <Link
                  href="/docs"
                  className="inline-flex items-center gap-2 px-4 py-2 bg-slate-100 text-slate-700 rounded-lg hover:bg-slate-200 transition"
                >
                  View API Documentation
                </Link>
              </div>
            </div>
          </section>

          {/* Full Documentation Link */}
          <section className="bg-blue-50 rounded-xl p-6 border border-blue-200">
            <h3 className="text-lg font-semibold text-slate-900 mb-2">Complete Documentation</h3>
            <p className="text-slate-600 mb-4">
              For detailed information about backup architecture, API endpoints, restore procedures,
              and troubleshooting, view the complete backup strategy documentation.
            </p>
            <a
              href="https://github.com/nextmavens/next-mavens-flow/blob/main/docs/backup-strategy/README.md"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 text-blue-700 hover:text-blue-800 font-medium"
            >
              View Full Backup Documentation
              <ArrowLeft className="w-4 h-4 rotate-180" />
            </a>
          </section>
        </div>
      </main>
    </div>
  )
}
